### ISSUE TITLE
Is License BSD or Apache 2

### ISSUE THREAD

**Issue by ogirardot** [groupon/sparklint#22]
Hi, 
In the pom.xml the license is specified as being a BSD license ( 3 clause ) but the LICENSE file is an Apache 2 license.
Which one did you choose ?

**Comment by swhitear** [comment]
Apache, the file headers are correct, good eyes :-) 
I have a PR out for the change (https://github.com/groupon/sparklint/pull/23).

**Comment by ogirardot** [comment]
cool thx, I'll update the build.sbt file I'm crafting
