### ISSUE TITLE
com.groupon.sparklint doesn't exist on central repository

### ISSUE THREAD

**Issue by matmichsyx** [groupon/sparklint#24]
--conf spark.extraListeners=com.groupon.sparklint.SparklintListener --packages com.groupon.sparklint:sparklint:1.0.2 doesn't work since com.groupon.sparklint doesn't exist (yet)

**Comment by ogirardot** [comment]
I think it's related to #3

**Comment by matmichsyx** [comment]
Is there a way around?

**Comment by roboxue** [comment]
Hi @matmichsyx ! Currently you can 

1. Do `mvn install` on your laptop, add dependency to your spark project, then package a fat jar that includes Sparklint, then submit this jar with `--conf spark.extraListeners=com.groupon.sparklint.SparklintListener` (Basically the sparklint source code will be bundled in your jar)
2. Or you can get a taste of it using server mode + event log files per README.

We will solve the sonatype chore ASAP. I've been on vacation for a few days (with limited internet access) thus I got delayed. Probably next Monday or Tuesday I'll complete #3 and let you know.

Thanks for your interest!!

**Comment by roboxue** [comment]
We've got version 1.0.3.1 out on maven; version 1.0.4 will be stable, since I found some bug these days in live mode that I'd like to address.

**Comment by swhitear** [comment]
Issue resolved with publication to nexus.
