### ISSUE TITLE
Empty reply from server on port 23763

### ISSUE THREAD

**Issue by landier** [groupon/sparklint#28]
Hello,

I succeeded in starting my Spark application with SparkLint as an extraListener but I'm getting no response from the SparkLint web server on port 23763.

I get the same issue in both yarn-client and yarn-cluster modes.

Any idea what is going wrong?

NB: I started the Spark app with following parameters:
```
spark-submit ...
--jars sparklint/target/jar-with-dependencies-sparklint-1.0.3-SNAPSHOT.jar \
--conf spark.extraListeners=com.groupon.sparklint.SparklintListener \
...
```

**Comment by roboxue** [comment]
Hi @landier in yarn-cluster, you'll need to find out your driver node's address (lets say it is worker123.example.com) and visit worker123.example.com:23763. The stdout of your drivernode log should have some sparklint log inside to verify the port it actually uses.  In yarn-client, you'll need to hit the job submitter box's port 23763. Are these the cases you've tried?

Could you verify that you can find your app's stdout log (with sparklint content inside) on driver node?

Another situation could be some other task is occupying port 23763, so Sparklint will go with the next port 23764 instead.

**Comment by landier** [comment]
Hello @roboxue ,

Yes these are the cases I tried. I can see that the Sparklint listener is registered when the application start from the application driver stdout. I could see that the port 23764 was being opened from the stdout as well from a netstat command.

The issue is really that no byte is being sent out from the Sparklint web server for us. :/

**Comment by roboxue** [comment]
I think this could be related to interface/port bindings. The fact that logs are displaying and without exceptions, and no logs are displayed showing incoming traffic means there likely exists a network config issue so the server is not exposed to external network.

Could you try curl localhost:[port] on the job submitting box during yarn-client mode? Do that work?

Here is the code that server will log every incoming requests as the first thing to do for each request:
https://github.com/groupon/sparklint/blob/develop/src/main/scala/com/groupon/sparklint/server/RoutingMap.scala#L35


This is the code I used to instruct the server listen to 0.0.0.0:[port], basically it means every network interface on the machine. Try change it to other IP (like the host's actual IP), and see if it solves your problem

https://github.com/groupon/sparklint/blob/develop/src/main/scala/com/groupon/sparklint/server/AdhocServer.scala#L80
