### ISSUE TITLE
Setup public sonatype

### ISSUE THREAD

**Issue by roboxue** [groupon/sparklint#3]

**Comment by ogirardot** [comment]
someone needs to create the account (it would be better if it's a groupon person, since the organization is com.groupon), there might already be some kind of owner of the "com.groupon" path in sonatype no ?

I'll do the build coding in the sbt PR

**Comment by roboxue** [comment]
We have accounts and almost everything. I just need to go back to office next week and finish the final releasing.

**Comment by roboxue** [comment]
Finished in #30
