### ISSUE TITLE
com.groupon.sparklint#sparklint;1.0.2: not found (UNRESOLVED DEPENDENCIES)

### ISSUE THREAD

**Issue by weineran** [groupon/sparklint#42]
I am trying to run sparklint in Live mode by simply adding the --conf and --packages parameters to my submit command (as given in the README).

I am getting an unresolved dependency message.

`com.groupon.sparklint#sparklint;1.0.2: not found`

Is there anything special I need to do to help Spark find this package?

Additional info:
I am running this on a yarn cluster

**Comment by roboxue** [comment]
Hi @weineran I've just made a lot of build system changes these days. If you are using spark1.6.1 ~ 2.0.2, try the new description in readme "com.groupon.sparklint:sparklint-spark161_2.10:1.0.4". You can substitute spark161 with the actual spark version you are using by removing the dots. If your spark is 2.11, replace 2.10 with 2.11 correspondingly.

Please let me know if you still have problem loading the jar. 

P.S. There is an off-by-one bug in live listener mode I'm yet to fix #31, hopefully you don't enter that today :)

**Comment by roboxue** [comment]
Should have been resolved now, since maven central has finished synchronizing

![image](https://cloud.githubusercontent.com/assets/4080835/20978472/a3a45dce-bc6e-11e6-9bd0-36d9533693b3.png)
