### ISSUE TITLE
Custom port for live mode doesn't work

### ISSUE THREAD

**Issue by jahubba** [groupon/sparklint#73]
There are two issues with setting custom port when running SparklintListener on driver (live mode)

1.  SparklintListener doesn't start server for port, so it always uses default port.
2.  Spark will not add the sparklint.port to SparkConf because it doesn't start with "spark.", you can add programmatically but is ignored on command line.

**Comment by roboxue** [comment]
Thanks for reporting this! I'll try to verify this. I remember I was able to use --conf not started with spark long time ago, will double check

**Comment by jahubba** [comment]
thanks @roboxue !
